### ISSUE TITLE
Cert not found

### ISSUE THREAD

**Issue by jobisoft** [grierforensics/Great-DANE-Thunderbird#1]
Hi,

if I understood it correct, I could select "Grier Forensics" as DANE SMIMEA Engine and try the plugin without having to install my own Engine on my own server? 

If I do so, I see a small popup box when trying to send an encrypted mail to a user who has his cert in the DNS but which is missing on my system. But no cert is retrieved. However in the console I see 

fetchCertsForEmailAddress error: Not Found

If I use your web service

http://dst.grierforensics.com/#/dane/

the cert is found. Any idea what I am doing wrong? If you write to my public email address, I will respond and tell you which email address I was testing with. It is not mine, so I cannot simply post it here.

**Comment by jobisoft** [comment]
I am using Add-On version 1.0.1 and if I click on "Test Connection" in the settings dialog, while "Grier Forensics" ist selected, I get "Error!"

**Comment by naegelejd** [comment]
This is just an issue with our hosted Great DANE Engine. We're not quite prepared to host a public instance, but I just made sure it's up and running so you can use it. Try "Test Connection" for the "Grier Forensics" instance now and it should work.

**Comment by jobisoft** [comment]
AWESOME! :-) It works! Nice. Now I will try to set up my own engine.

**Comment by soulsymphonies** [comment]
I actually got running my own engine on my Windows 10 machine, and I configured Thunderbird Addon 1.0.1 to use it, but it does not find certificates for my email adresses, also the SMIMEA records are alright and your webservice actually finds them.

I opened and issue on the Great-DANE-Engine plugin:
https://github.com/grierforensics/Great-DANE-Engine/issues/5

Have the most wonderful Easter.
Robert Christian Strasser

**Comment by jobisoft** [comment]
I think that is a different issue, since I reported problems with the hosted engine, which works now. For clarity, I close this issue as solved.
